import { Activity, Lightbulb } from "lucide-react";
import PanelHeader from "../../../components/PanelHeader";
import RelevanceMeter from "../../../components/RelevanceMeter";
import { MOCK_NEWS } from "../../../data/mockData";

// News feed for the last 60 days, ranked by interview relevance.
// Each item has a "how to use" tip generated by the strategy agent.

export default function NewsTab() {
  return (
    <div style={{
      background: "var(--bg-panel)",
      border: "1px solid var(--border-subtle)",
      borderRadius: 8, overflow: "hidden",
    }}>
      <PanelHeader
        icon={Activity}
        title="News feed"
        tag="LAST 60 DAYS · RANKED BY RELEVANCE"
      />
      <div style={{ padding: 8 }}>
        {MOCK_NEWS.map((n, i) => (
          <NewsItem
            key={i}
            news={n}
            isLast={i === MOCK_NEWS.length - 1}
          />
        ))}
      </div>
    </div>
  );
}

function NewsItem({ news, isLast }) {
  return (
    <div style={{
      padding: 18,
      borderBottom: isLast ? "none" : "1px solid var(--border-subtle)",
    }}>
      {/* Title + relevance score */}
      <div style={{
        display: "flex", justifyContent: "space-between",
        gap: 16, alignItems: "flex-start", marginBottom: 8,
      }}>
        <div style={{
          fontFamily: "var(--font-serif)", fontSize: 17, fontWeight: 600,
          lineHeight: 1.3, letterSpacing: "-0.01em", flex: 1,
        }}>
          {news.title}
        </div>
        <RelevanceMeter score={news.relevance} />
      </div>

      {/* Source + date */}
      <div style={{
        fontFamily: "var(--font-mono)", fontSize: 11,
        color: "var(--fg-muted)", marginBottom: 10,
      }}>
        {news.source} · {news.date}
      </div>

      {/* Strategy tip */}
      <div style={{
        padding: 12,
        background: "var(--bg-base)",
        borderLeft: "2px solid var(--accent)",
        borderRadius: "0 4px 4px 0",
        fontSize: 13, color: "var(--fg-secondary)", lineHeight: 1.5,
      }}>
        <Lightbulb size={12} style={{
          display: "inline", marginRight: 6, color: "var(--accent)",
        }} />
        <strong style={{ color: "var(--fg-primary)" }}>How to use:</strong>{" "}
        {news.tip}
      </div>
    </div>
  );
}
