tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f4f7",
        "tertiary-container": "#f8f8b3",
        "on-tertiary": "#fdfdb8",
        "on-tertiary-container": "#5e5e29",
        "outline-variant": "#acb3b7",
        "on-error": "#fff7f6",
        "error": "#a73b21",
        "on-surface": "#2c3437",
        "secondary-fixed-dim": "#c7d5ed",
        "on-primary-container": "#00600e",
        "tertiary-fixed-dim": "#e9e9a6",
        "inverse-on-surface": "#9a9d9f",
        "on-tertiary-fixed": "#4b4c19",
        "primary-dim": "#00610f",
        "on-primary": "#eaffe1",
        "on-error-container": "#6e1400",
        "surface-container": "#eaeff2",
        "primary-container": "#81fd78",
        "primary-fixed": "#81fd78",
        "on-secondary": "#f8f8ff",
        "on-surface-variant": "#596064",
        "surface-dim": "#d4dbdf",
        "inverse-surface": "#0b0f10",
        "surface-container-high": "#e3e9ed",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006f12",
        "secondary": "#526074",
        "error-container": "#fd795a",
        "on-primary-fixed": "#004b09",
        "inverse-primary": "#81fd78",
        "on-background": "#2c3437",
        "primary-fixed-dim": "#73ee6b",
        "on-secondary-fixed-variant": "#4e5c71",
        "background": "#f7f9fb",
        "tertiary-fixed": "#f8f8b3",
        "tertiary-dim": "#555622",
        "surface-variant": "#dce4e8",
        "surface-container-highest": "#dce4e8",
        "secondary-fixed": "#d5e3fc",
        "secondary-container": "#d5e3fc",
        "error-dim": "#791903",
        "on-tertiary-fixed-variant": "#686933",
        "tertiary": "#61622c",
        "on-secondary-fixed": "#324053",
        "on-primary-fixed-variant": "#006b11",
        "secondary-dim": "#465468",
        "on-secondary-container": "#455367",
        "outline": "#747c80",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "primary": "#006f12"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        md: "0.375rem"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    }
  }
};